MAX_SPEED = 10
MIN_SPEED = 5
START_SPEED = 6 
REFEREE_MAX_SPEED  = 6
REFEREE_START_SPEED  = 4
REFEREE_ACCELERATION = 0.5 -- increase speed every 20 meters
PERFECT_POSITION =  50
PERFECT_MARGIN = 20
GOOD_RANGE = 20

-- Shot power properties
MINIMAL_SHOT_POWER = 0.2
WEAK_SHOT_POWER = 0.35
-- 0542842466
KICK_TIMEUOT_DURATION_AUTO = 3750 --375
KICK_ASSIST_DURATION_AUTO = 1

KICK_TIMEUOT_DURATION = 750 --375
KICK_ASSIST_DURATION = 100

EASY_MODE_LENGTH = 100
-- easy mode probabilites
P_DOG  = 20
P_KID  = 20	
P_TALL_KID  = 10
P_DOUBLE_KID = 7
P_BANANA  = 5
P_CAN  = 5
P_BIRD  = 5
P_BIRD_DOG  = 10
P_BIRD_KID  = 6
P_GOAL = 8

IS_AUTO_KICK = true


SHADOW_MAX_SCALE = 0.3
LITTLE_RUNNER_SPEED = 9.5

LEVELS_COUNT = 5
ULTRA_MODE_PERFECTS = 8
ULTRA_MODE_DURATION = 6000

TUTORIAL_FIRST_STAGE_COUNT = 1
TUTORIAL_FIFTH_STAGE_COUNT = 4

START_TUTORIAL_STAGE = 1
LAST_TUTORIAL_STAGE = 6

BALL_X = 180

END_GAME_WHEN_DEF_TOUCH = true
SHOP_FILE = "strika.dat"--"l1.dat" -- 32		
GAME_DATA_FILE = "supa.dat" -- "ldr.dat" --22

